# Set environment variables
env:
  global:
    - secure: "eNufz0915oMHd4cNbvo+YysNgJSP3IFrsWPFkVtg2S/L3hCv9+sTto/yuX00\nHvaJ1lcvak2DkiQmslJubcjpGNOysjp6rjhY92YodZs+wZwsrevjoanj9qWH\nwHz2eM1N6fvebMmzNS9fwwFmY3DiCDwBoTssz8aLs0etg+2xVBw="

  matrix: 
    - secure: "eNufz0915oMHd4cNbvo+YysNgJSP3IFrsWPFkVtg2S/L3hCv9+sTto/yuX00\nHvaJ1lcvak2DkiQmslJubcjpGNOysjp6rjhY92YodZs+wZwsrevjoanj9qWH\nwHz2eM1N6fvebMmzNS9fwwFmY3DiCDwBoTssz8aLs0etg+2xVBw="

# use c and gcc
language: c
compiler: gcc

# only build branches on whitelist
#branches:
#  only:
#    - setup-ci
#    - master

# install all vnc-related dependencies
before_install:
  - sudo apt-get install libcairo2-dev
  - git clone git://github.com/cmujedi/libguac.git
  - cd libguac
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - sudo apt-get install tomcat6
  - sudo apt-get install libvncserver0
  - sudo apt-get install libvncserver-dev
  - sudo apt-get install libfreerdp1
  - sudo apt-get install libvorbisenc2

# before build script, run autoreconf
before_script: autoreconf -i

# Default is "./configure && make && make test", but no tests yet
script: "./configure && make"

# after build script, run make install
after_success: 
  - sudo make install
  - curl -s -o output.txt $IRC_TREELOGIC_CHANNEL_TOKEN -d "service=TravisCI" -d "message=$TRAVIS_REPO_SLUG $TRAVIS_BUILD_NUMBER ( $TRAVIS_BRANCH - $TRAVIS_COMMIT ) - Passed" -d "url=https://grove.io/app" -d "icon_url=https://secure.travis-ci.org/$TRAVIS_REPO_SLUG.png"


# after build script, run make install
after_failure: 
   - curl -s -o output.txt $IRC_TREELOGIC_CHANNEL_TOKEN -d "service=TravisCI" -d "message=$TRAVIS_REPO_SLUG $TRAVIS_BUILD_NUMBER ( $TRAVIS_BRANCH - $TRAVIS_COMMIT ) - Failed" -d "url=https://grove.io/app" -d "icon_url=https://secure.travis-ci.org/$TRAVIS_REPO_SLUG.png"

# add notification email addresses
notifications:
  email:
    recipients:
      - cmujedi@west.cmu.edu
  webhooks:
    - secure: "eNufz0915oMHd4cNbvo+YysNgJSP3IFrsWPFkVtg2S/L3hCv9+sTto/yuX00\nHvaJ1lcvak2DkiQmslJubcjpGNOysjp6rjhY92YodZs+wZwsrevjoanj9qWH\nwHz2eM1N6fvebMmzNS9fwwFmY3DiCDwBoTssz8aLs0etg+2xVBw="

